INSERT INTO users (user_name, user_password) VALUES ('Billiam667', '2')
INSERT INTO users (user_name, user_password) VALUES ('Hilarious68', 'password69')
INSERT INTO users (user_name, user_password) VALUES ('KatAttack', '5oranges')

INSERT INTO pets (pet_type, pet_name, user_id) VALUES ('cat', 'Dandy', '1')
INSERT INTO pets (pet_type, pet_name, user_id) VALUES ('rat', 'Sans', '1')
INSERT INTO pets (pet_type, pet_name, user_id) VALUES ('cat', 'Amelia', '2')
INSERT INTO pets (pet_type, pet_name, user_id) VALUES ('cat', 'Chamblee', '2')
INSERT INTO pets (pet_type, pet_name, user_id) VALUES ('cat', 'Tilly', '2')
INSERT INTO pets (pet_type, pet_name, user_id) VALUES ('cat', 'Cora', '3')