INSERT INTO users (user_name, user_password) VALUES ('Billiam667', '2');
INSERT INTO users (user_name, user_password) VALUES ('Hilarious68', 'password69');
INSERT INTO users (user_name, user_password) VALUES ('KatAttack', '5oranges');

INSERT INTO pets (pet_type, pet_name, pet_age, pet_birthday, fur_color, fave_nap, fave_food, fave_toy, fave_scratch, fave_walk, fave_window, fave_feature, bowl_empty, user_id) VALUES ('Cat', 'Dandy', 5, 'June', 'Orange', 'On my dads face', 'Rachel Ray Nourishments', 'My sushis!!!', 'Under my chin!!', 'I love windows, they are warm.', 'Everyone notices how sweet I am!', 'I yell at my dad until he fills it, and then I will just stare at it', 1);
INSERT INTO pets (pet_type, pet_name, pet_age, pet_birthday, fur_color, fave_nap, fave_food, fave_toy, fave_scratch, fave_walk, fave_window, fave_feature, bowl_empty, user_id) VALUES ('Rat', 'Sans', 2, 'December','Black and white', 'I sleep under my bedding!!!', 'Peanuts! Leave the shell on, thats my favorite part!', 'I really like toilet paper rolls', 'I love my ears to be rubbed', 'I like to be outside my cage!', 'Idk what a window is!', 'I make a lot of happy noises', 'I climb on top of my cage!', 1);
INSERT INTO pets (pet_type, pet_name, pet_age, pet_birthday, fur_color, fave_nap, fave_food, fave_toy, fave_scratch, fave_walk, fave_window, fave_feature, bowl_empty, user_id) VALUES ('cat', 'Amelia', 4, 'June 2014', 'under the blankets', 'cookies', 'rolly ball track', 'under my chin', 'I am from the streets', 'they are alright', 'my whacky whiskers', "eat my kitten's food", 2);
INSERT INTO pets (pet_type, pet_name, pet_age, pet_birthday, fur_color, fave_nap, fave_food, fave_toy, fave_scratch, fave_walk, fave_window, fave_feature, bowl_empty, user_id) VALUES ('cat', 'Chambles', 8, 'June 2010', 'Calico', 'kitty beach', 'all food', 'my darth vader mouse', 'above my tail', 'I love to roll on the warm pavers in the courtyard.', 'love em', 'my eyes', 'sit by it and whine', 2);
INSERT INTO pets (pet_type, pet_name, pet_age, pet_birthday, fur_color, fave_nap, fave_food, fave_toy, fave_scratch, fave_walk, fave_window, fave_feature, bowl_empty, user_id) VALUES ('cat', 'Tilly', 2, 'August 2015', 'tabby', 'the tower', 'watermelon', 'cardboard wire bouncy thingy', 'between my ears', 'so scare', 'yeah', 'my tiny little voice', 'dig in it', 2);
INSERT INTO pets (pet_type, pet_name, pet_age, pet_birthday, fur_color, fave_nap, fave_food, fave_toy, fave_scratch, fave_walk, fave_window, fave_feature, bowl_empty, user_id) VALUES ('cat', 'Cora', 6, 'April 2012', 'black and white', 'wherever', 'chicken', 'the world is my toy', 'between my shoulders', 'outside??', 'lol windows', 'T H I C C', 'yell', 3);